- alias: "MagicMorning"
  trigger:
    platform: time
    at: '07:00'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - switch.Zolder

- alias: "WakeUp"
  trigger:
    - platform: time
      at: '07:00:00'
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - group.Beneden
          - light.Slaapkamer_2
          - light.Cyberhok
          - switch.Badkamer
          - switch.Gang1ste

- alias: "Vertrokken"
  trigger:
    - platform: time
      at: '8:45:00'
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - group.Beneden
          - group.1ste
          - group.Zolder

- alias: "MagicEvening"
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - switch.Zolder


- alias: "Thuiskomst"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - group.Beneden
          - switch.Gang1ste
          - light.Slaapkamer_2
          - light.Cyberhok
          - switch.Badkamer

- alias: "Slapen"
  trigger:
    - platform: time
      at: '23:00:00'
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - group.Beneden
          - group.1ste
          - group.Zolder

#- alias: "Schuur"
#  trigger:
#    - platform: state
#      entity_id: device.vphone
#      to: 'home'    
#  action:
#    - service: homeassistant.turn_off
#      data:
#        entity_id:
#          - switch.Schuur

- alias: "helmhome"
  initial_state: False
  hide_entity: False
  trigger:
    - platform: state
      entity_id: device.scala_rider_q1, device.v_phone
      from: 'not_home'
      to: 'home'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - light.Cyberhok
          - light.Schuur
       
- alias: "helmweg"                 
  initial_state: True
  hide_entity: False
  trigger:                                   
    - platform: state
      entity_id: device.scala_rider_q1, device.v_phone
      from: 'home'              
      to: 'not_home'
  action:         
    - service: homeassistant.turn_off
      data:                
        entity_id:            
          - light.Cyberhok
          - light.Schuur                     
               

