- alias: "WakeUp"
  trigger:
    - platform: time
      at: '07:00:00'
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - group.Beneden
          - light.Slaapkamer
          - light.Cyberhok
          - switch.Badkamer
          - switch.Gang1ste

- alias: "Vertrokken"
  trigger:
    - platform: time
      at: '8:45:00'
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - group.Beneden
          - group.1ste
          - group.Zolder

- alias: "Thuiskomst"
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
#  condition:
#    condition: state
#    entity_id: 'binary_sensor.workday_sensor'
#    state: 'on'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - group.Beneden
          - switch.Gang1ste
          - light.Slaapkamer
          - light.Cyberhok
          - switch.Badkamer

- alias: "Slapen"
  trigger:
    - platform: time
      at: '23:00:00'
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - group.Beneden
          - group.1ste
          - group.Zolder

- alias: "testaan"
  trigger:
    platform: state
    entity_id: device_tracker.vphone
    from: 'away'
    to: 'home'
  action: 
    - service: homeassistant.turn_on
      data:
        entity_id:
          - switch.schuur

- alias: "testuit"
  trigger:                                                                                                                
    platform: state                                                                                                       
    entity_id: device_tracker.vphone                                                                                      
    from: 'home'
    to: 'away'
  action:                                                                                                                 
    - service: homeassistant.turn_off
      data:                                                                                                               
        entity_id:                                                                                                        
          - switch.schuur             
 
