- alias: 'Thuis'
  trigger:
    platform: state
    entity_id: device_tracker.1v1
    from: 'not_home'
    to: 'home'
  condition: 
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-0:30:00"
      - condition: state
        entity_id: group.Beneden
        state: 'off'
  action:
    service: switch.turn_on
    entity_id: group.Beneden

- alias: 'Weg'
  trigger:
    platform: state
    entity_id: device_tracker.1v1
    from: 'home'
    to: 'not_home'
  condition:
    condition: and  
    conditions:
      - condition: sun
        after: sunrise
        after_offset: "-0:30:00"
      - condition: state
        entity_id: group.Beneden  
        state: 'off'
  action:
    service: switch.turn_off
    entity_id: group.Zolder

- alias: 'Leave Home notification'
  trigger:
    platform: zone
    event: leave
    zone: zone.home
    entity_id: device_tracker.1v1
  condition:
    condition: time
    after: '07:00'
  action:
    service: notify.notify
    data:
      message: '1v1 left the house'

