homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Amsterdam

  customize: !include customize.yaml

frontend:
config:
http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: !secret base_url

updater:
  include_used_components: true

discovery:

ios:

conversation:

history:

logbook:

map:

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_user
  password: !secret mqtt_pass  

sun:

sensor:
  - platform: yr
  - platform: moon

binary_sensor:
  - platform: iss
  - platform: workday
    country: NL
    workdays: [ mon, tue, wed, thu, fri ]

weather:
  - platform: buienradar
    name: !secret location
    latitude: !secret latitude
    longitude: !secret longitude
    forecast: True

camera:
  - platform: generic
    name: Meteo
    still_image_url: https://www.yr.no/place/Netherlands/North_Brabant/Eindhoven/meteogram.svg
    content_type: 'image/svg+xml'
    
light:
  - platform: flux_led
    automatic_add: true
    
#google:
#  client_id: !secret google_client_id
#  client_secret: !secret google_client_secret

#panel_iframe:
#  configurator:
#    title: Configurator
#    icon: mdi:wrench
#    url: http://hassio.local:3218
 
#tts:
#  - platform: google_translate
#    service_name: google_say

cloud:

system_health:

switch: !include switches.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
device_tracker: !include device_tracker.yaml


